# Generated by Django 2.2.16 on 2022-06-13 14:16

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220607_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientamount',
            name='amount',
            field=models.PositiveIntegerField(validators=[api.validators.ingred_nums]),
        ),
    ]
